from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd
import numpy as np

columns_list = ['income', 'debt_to_income_ratio', 'applicant_credit_score_type', 'co-applicant_credit_score_type', 'loan_amount', 'loan_purpose', 'loan_to_value_ratio', 'loan_term', 'preapproval', 'lien_status', 'prepayment_penalty_term', 'intro_rate_period', 'negative_amortization', 'interest_only_payment', 'balloon_payment', 'property_value', 'construction_method', 'occupancy_type', 'county_code', 'census_tract', 'applicant_ethnicity-1', 'applicant_ethnicity-2', 'applicant_ethnicity-3', 'applicant_ethnicity-4', 'applicant_ethnicity-5', 'applicant_race-1', 'applicant_race-2', 'applicant_race-3', 'applicant_race-4', 'applicant_race-5', 'applicant_sex','applicant_age', 'action_taken']

int_types = ['applicant_ethnicity-1',
       'applicant_ethnicity-2', 'applicant_ethnicity-3',
       'applicant_ethnicity-4', 'applicant_ethnicity-5', 'applicant_race-1',
       'applicant_race-2', 'applicant_race-3', 'applicant_race-4',
       'applicant_race-5', 'applicant_sex', 'action_taken']
float_types=['loan_amount','loan_to_value_ratio', 'interest_rate', 'rate_spread', 'income', 'debt_to_income_ratio', 'loan_to_value_ratio']

object_types=[]

data = pd.read_csv("state_CA.csv", usecols= columns_list)



<ipython-input-2-3ad6f845d460>:15: DtypeWarning: Columns (22,31,32,33,38,46,77) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/state_CA.csv", usecols= columns_list)


In [ ]:
len(columns_list)

33

In [ ]:
columns_to_check_for_na = ['county_code', 'census_tract', 'preapproval',
       'loan_purpose', 'lien_status', 'loan_amount', 'loan_to_value_ratio', 'loan_term', 'prepayment_penalty_term',
       'intro_rate_period', 'negative_amortization', 'interest_only_payment',
       'balloon_payment', 'property_value', 'construction_method',
       'occupancy_type', 'income', 'debt_to_income_ratio',
       'applicant_credit_score_type', 'co-applicant_credit_score_type',
       'applicant_ethnicity-1', 'applicant_race-1', 'applicant_sex']

data= data.dropna(subset=columns_to_check_for_na)


In [ ]:
data = data[data!= 'Exempt']
data = data[data!= '1111']
data = data[data!= 1111]
data = data[data!= '8888']
data = data[data!= 8888]

In [ ]:
data = data[data!= 'NaN']
data = data[data!= 'nan']

In [ ]:
# Update action_taken values
data['action_taken'] = data['action_taken'].replace({1: 1, 2: 1, 3: 0, 7: 0})

# Drop rows with action_taken values of 4, 5, 6, or 8
data = data[~data['action_taken'].isin([4, 5, 6, 8])]
data = data[~data['applicant_ethnicity-1'].isin([3, 4])]
data = data[~data['applicant_sex'].isin([3, 4, 6])]



In [ ]:
action_taken_counts = data['action_taken'].value_counts()
print(action_taken_counts)

action_taken
0    32992
1    31881
Name: count, dtype: int64


In [ ]:
data['debt_to_income_ratio']= data['debt_to_income_ratio'].replace({
    '<20%': '0',
    '>60%': '60',

    '30%-<36%': '30',
    '20%-<30%': '20',
    '50%-60%': '50'
})

num_elements_per_range = min(data['debt_to_income_ratio'].value_counts())



In [ ]:

replacement_ranges = {
    '37': [37,38,39,40,41,42],
    '43': [43,44,45,46,47,48,49],
}

for key,value in replacement_ranges.items():
  selected_rows= data['debt_to_income_ratio'].astype(float).between(min(value), max(value))
  data.loc[selected_rows, 'debt_to_income_ratio'] = key



In [ ]:
for i in range(1, 6):
        race_col = f'applicant_race-{i}'
        data[race_col] = data[race_col].replace({1: 1, 2: 2, 21:2, 22:2, 23:2, 24:2, 25:2, 26:2, 27:2, 3: 3, 4: 4, 41:4, 42: 4, 43: 4, 44: 4})

for i in range(1, 6):
        race_col = f'applicant_ethnicity-{i}'
        data[race_col] = data[race_col].replace({1: 1, 2: 0, 11:1, 12:1, 13:1, 14:1})

data['applicant_ethnicity'] = (data[['applicant_ethnicity-1', 'applicant_ethnicity-2', 'applicant_ethnicity-3', 'applicant_ethnicity-4', 'applicant_ethnicity-5']].sum(axis=1) >= 1).astype(int) + 1
data.drop(['applicant_ethnicity-1', 'applicant_ethnicity-2', 'applicant_ethnicity-3', 'applicant_ethnicity-4', 'applicant_ethnicity-5'],  axis=1, inplace=True)


In [ ]:
data

county_code  census_tract  action_taken  preapproval  loan_purpose  \
54108         6085.0  6.085504e+09             1            2             1   
54116         6059.0  6.059063e+09             1            2             1   
54131         6037.0  6.037262e+09             1            2             1   
54139         6059.0  6.059063e+09             1            2             1   
64997         6085.0  6.085508e+09             1            2             1   
...              ...           ...           ...          ...           ...   
1547658       6071.0  6.071002e+09             1            2             1   
1547660       6059.0  6.059052e+09             1            2             1   
1547661       6037.0  6.037403e+09             1            2             1   
1547662       6037.0  6.037431e+09             1            2            32   
1547663       6059.0  6.059052e+09             1            2             1   

         lien_status  loan_amount loan_to_value_ratio loan_term  \
54108              1    1085000.0                 NaN       NaN   
54116              1    1955000.0                 NaN       NaN   
54131              1    3045000.0                 NaN       NaN   
54139              1    2625000.0                 NaN       NaN   
64997              1    1725000.0                65.0     360.0   
...              ...          ...                 ...       ...   
1547658            1     395000.0                 NaN       NaN   
1547660            1    1025000.0                 NaN       NaN   
1547661            1     545000.0                 NaN       NaN   
1547662            1     875000.0                 NaN       NaN   
1547663            1    1275000.0                 NaN       NaN   

        prepayment_penalty_term  ... applicant_credit_score_type  \
54108                       NaN  ...                         NaN   
54116                       NaN  ...                         NaN   
54131                       NaN  ...                         NaN   
54139                       NaN  ...                         NaN   
64997                      18.0  ...                         9.0   
...                         ...  ...                         ...   
1547658                     NaN  ...                         NaN   
1547660                     NaN  ...                         NaN   
1547661                     NaN  ...                         NaN   
1547662                     NaN  ...                         NaN   
1547663                     NaN  ...                         NaN   

         co-applicant_credit_score_type  applicant_race-1  applicant_race-2  \
54108                               NaN               2.0               2.0   
54116                               NaN               5.0               NaN   
54131                               NaN               5.0               NaN   
54139                               NaN               5.0               NaN   
64997                              10.0               2.0               NaN   
...                                 ...               ...               ...   
1547658                             NaN               2.0               2.0   
1547660                             NaN               2.0               2.0   
1547661                             NaN               2.0               2.0   
1547662                             NaN               2.0               2.0   
1547663                             NaN               2.0               2.0   

        applicant_race-3  applicant_race-4  applicant_race-5  applicant_sex  \
54108                NaN               NaN               NaN              1   
54116                NaN               NaN               NaN              2   
54131                NaN               NaN               NaN              1   
54139                NaN               NaN               NaN              1   
64997                NaN               NaN               NaN              1   
...            

In [ ]:
def combine_race(row):
    races = []
    for i in range(1, 6):
        race_col = f'applicant_race-{i}'
        if pd.notna(row[race_col]) and row[race_col] in [1,2,3,4,5]:
            races.append(row[race_col])
    return races


In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer

app_race = data.apply(combine_race, axis=1)
mlb = MultiLabelBinarizer()
race_binarized = mlb.fit_transform(app_race)
data=data.drop(columns=['applicant_race-1', 'applicant_race-2', 'applicant_race-3', 'applicant_race-4', 'applicant_race-5'])

In [ ]:
data.columns

Index(['county_code', 'census_tract', 'action_taken', 'preapproval',
       'loan_purpose', 'lien_status', 'loan_amount', 'loan_to_value_ratio',
       'loan_term', 'prepayment_penalty_term', 'intro_rate_period',
       'negative_amortization', 'interest_only_payment', 'balloon_payment',
       'property_value', 'construction_method', 'occupancy_type', 'income',
       'debt_to_income_ratio', 'applicant_credit_score_type',
       'co-applicant_credit_score_type', 'applicant_sex', 'applicant_age',
       'applicant_ethnicity'],
      dtype='object')

In [ ]:
race_binarized

array([[0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       ...,
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0]])

In [ ]:
import numpy as np
race_sums = race_binarized.sum(axis=1)
data['Mixed'] = (race_sums > 1).astype(int)

data = data[race_sums > 0]
race_binarized = race_binarized[race_sums > 0]

In [ ]:
for i, race in enumerate(['AI or AN', 'Asian', 'Black or AA', 'NH or PI', 'White']):
    data[f'{race}'] = race_binarized[:, i]

In [ ]:
race_columns = ['AI or AN', 'Asian', 'Black or AA', 'NH or PI', 'White']
result_a =data[race_columns].sum(axis=1)<1
off_rows = data[result_a]
print(off_rows)

Empty DataFrame
Columns: [county_code, census_tract, action_taken, preapproval, loan_purpose, lien_status, loan_amount, loan_to_value_ratio, loan_term, prepayment_penalty_term, intro_rate_period, negative_amortization, interest_only_payment, balloon_payment, property_value, construction_method, occupancy_type, income, debt_to_income_ratio, applicant_credit_score_type, co-applicant_credit_score_type, applicant_sex, applicant_age, applicant_ethnicity, Mixed, AI or AN, Asian, Black or AA, NH or PI, White]
Index: []

[0 rows x 30 columns]


In [ ]:
data.dropna(inplace=True)

In [ ]:
data['prepayment_penalty_term'] = data['prepayment_penalty_term'].astype(int)
data['intro_rate_period'] = data['intro_rate_period'].astype(int)

In [ ]:
x = 0
for column in data.columns:
  distinct_values = data[column].nunique()
  print(f"Column '{column}' has {distinct_values} distinct values", x)
  x+=1

Column 'county_code' has 57 distinct values 0
Column 'census_tract' has 8063 distinct values 1
Column 'action_taken' has 2 distinct values 2
Column 'preapproval' has 2 distinct values 3
Column 'loan_purpose' has 6 distinct values 4
Column 'lien_status' has 2 distinct values 5
Column 'loan_amount' has 186 distinct values 6
Column 'loan_to_value_ratio' has 26126 distinct values 7
Column 'loan_term' has 13 distinct values 8
Column 'prepayment_penalty_term' has 7 distinct values 9
Column 'intro_rate_period' has 9 distinct values 10
Column 'negative_amortization' has 2 distinct values 11
Column 'interest_only_payment' has 2 distinct values 12
Column 'balloon_payment' has 2 distinct values 13
Column 'property_value' has 1058 distinct values 14
Column 'construction_method' has 2 distinct values 15
Column 'occupancy_type' has 3 distinct values 16
Column 'income' has 1343 distinct values 17
Column 'debt_to_income_ratio' has 8 distinct values 18
Column 'applicant_credit_score_type' has 8 distinc

In [ ]:
import numpy as np
categorical_features = []
dicts = {}
x = 0
for column in data.columns:
  feature_dict= {}
  distinct_values = data[column].nunique()
  if column == 'action_taken' or column == 'Asian' or column == 'Black or AA' or column == 'NH or PI' or column == 'White':
    continue
  if column == 'AI or AN':
    feature_dict['AI or AN'] = x
    x+=1
    feature_dict['Asian'] = x
    x+=1
    feature_dict['Black or AA'] = x
    x+=1
    feature_dict['NH or PI'] = x
    x+=1
    feature_dict['White'] = x
    x+=1
    dicts['race'] = feature_dict
    continue
  elif distinct_values < 50 and distinct_values>2:
    categorical_features.append(column)
    distinct_ops = data[column].unique()
    for y in distinct_ops:
      feature_dict[y] = x
      x+=1
  elif distinct_values == 2:
    feature_dict['binary'] = x
    x+=1
  else:
    feature_dict['continuous'] = x
    x += 1
  dicts[column]=feature_dict

In [ ]:
print(dicts)

{'county_code': {'continuous': 0}, 'census_tract': {'continuous': 1}, 'preapproval': {'binary': 2}, 'loan_purpose': {1: 3, 31: 4, 2: 5, 32: 6, 4: 7, 5: 8}, 'lien_status': {'binary': 9}, 'loan_amount': {'continuous': 10}, 'loan_to_value_ratio': {'continuous': 11}, 'loan_term': {360.0: 12, 240.0: 13, '360': 14, '240': 15, '300': 16, '180': 17, 180.0: 18, 300.0: 19, '60': 20, '120': 21, '480': 22, '84': 23, '420': 24}, 'prepayment_penalty_term': {18: 25, 36: 26, 0: 27, 24: 28, 12: 29, 6: 30, 2: 31}, 'intro_rate_period': {60: 32, 1: 33, 84: 34, 299: 35, 120: 36, 3: 37, 12: 38, 6: 39, 9: 40}, 'negative_amortization': {'binary': 41}, 'interest_only_payment': {'binary': 42}, 'balloon_payment': {'binary': 43}, 'property_value': {'continuous': 44}, 'construction_method': {'binary': 45}, 'occupancy_type': {3: 46, 1: 47, 2: 48}, 'income': {'continuous': 49}, 'debt_to_income_ratio': {'50': 50, '30': 51, '37': 52, '43': 53, '60': 54, '20': 55, '0': 56, '36': 57}, 'applicant_credit_score_type': {9.0

In [ ]:
# = ['occupancy_type', 'preapproval','lien_status', 'balloon_payment', 'negative_amortization', 'interest_only_payment', 'debt_to_income_ratio','applicant_age', 'loan_purpose', 'applicant_credit_score_type', 'co-applicant_credit_score_type']

data_encoded = pd.get_dummies(data, columns=categorical_features)

In [ ]:
data = data_encoded

In [ ]:
list(data.columns)

['county_code',
 'census_tract',
 'action_taken',
 'preapproval',
 'lien_status',
 'loan_amount',
 'loan_to_value_ratio',
 'negative_amortization',
 'interest_only_payment',
 'balloon_payment',
 'property_value',
 'construction_method',
 'income',
 'applicant_sex',
 'applicant_ethnicity',
 'Mixed',
 'AI or AN',
 'Asian',
 'Black or AA',
 'NH or PI',
 'White',
 'loan_purpose_1',
 'loan_purpose_2',
 'loan_purpose_4',
 'loan_purpose_5',
 'loan_purpose_31',
 'loan_purpose_32',
 'loan_term_180.0',
 'loan_term_240.0',
 'loan_term_300.0',
 'loan_term_360.0',
 'loan_term_120',
 'loan_term_180',
 'loan_term_240',
 'loan_term_300',
 'loan_term_360',
 'loan_term_420',
 'loan_term_480',
 'loan_term_60',
 'loan_term_84',
 'prepayment_penalty_term_0',
 'prepayment_penalty_term_2',
 'prepayment_penalty_term_6',
 'prepayment_penalty_term_12',
 'prepayment_penalty_term_18',
 'prepayment_penalty_term_24',
 'prepayment_penalty_term_36',
 'intro_rate_period_1',
 'intro_rate_period_3',
 'intro_rate_period_

In [ ]:

# Separate the majority and minority classes
df_majority = data[data.action_taken == 0]
df_minority = data[data.action_taken == 1]

# Undersample the majority class without replacement
df_majority_undersampled = df_majority.sample(n=len(df_minority), random_state=42)

# Combine minority class with undersampled majority class
df_undersampled = pd.concat([df_minority, df_majority_undersampled])

# Shuffle the dataset to prevent the model from learning any order
df_undersampled = df_undersampled.sample(frac=1, random_state=42).reset_index(drop=True)


In [ ]:
 data = df_undersampled

In [ ]:
action_taken_counts = data['action_taken'].value_counts()
print(action_taken_counts)

action_taken
1    26720
0    26720
Name: count, dtype: int64


In [ ]:
continuous = ['county_code', 'census_tract', 'loan_amount', 'loan_to_value_ratio', 'property_value', 'income']
def weighted_euclidean(x, y, weights):
    return np.sqrt(np.sum(weights * (x - y) ** 2))

def weighted_hamming(x, y, weights):
    return np.sum(weights * (x != y))

In [ ]:
from numba import jit
import numpy as np

@jit(nopython=True)
def numba_weighted_euclidean(data, weights):
    n_samples = data.shape[0]
    dist_matrix = np.zeros((n_samples, n_samples))

    for i in range(n_samples):
        for j in range(n_samples):
            dist = 0.0
            for k in range(data.shape[1]):
                diff = data[i, k] - data[j, k]
                dist += (diff * diff) * weights[k]
            dist_matrix[i, j] = np.sqrt(dist)

    return dist_matrix


In [ ]:
@jit(nopython=True)
def numba_weighted_hamming_distance(data, weights):
    n_samples = data.shape[0]
    dist_matrix = np.zeros((n_samples, n_samples), dtype=np.float32)

    for i in range(n_samples):
        for j in range(i + 1, n_samples):
            # Calculate the weighted distance
            dist = 0.0
            for k in range(data.shape[1]):  
                if data[i, k] != data[j, k]:
                    dist += weights[k]  

            dist_matrix[i, j] = dist
            dist_matrix[j, i] = dist  # Symmetric matrix

    return dist_matrix

In [ ]:
from sklearn.model_selection import train_test_split

# Assuming 'action_taken' is the target variable


columns_with_na = data.columns[data.isna().any()].tolist()
X = data.drop('action_taken', axis=1)
y = data['action_taken']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
columns_with_na

[]

In [ ]:
X_test.columns

Index(['county_code', 'census_tract', 'preapproval', 'lien_status',
       'loan_amount', 'loan_to_value_ratio', 'negative_amortization',
       'interest_only_payment', 'balloon_payment', 'property_value',
       'construction_method', 'income', 'applicant_sex', 'applicant_ethnicity',
       'Mixed', 'AI or AN', 'Asian', 'Black or AA', 'NH or PI', 'White',
       'loan_purpose_1', 'loan_purpose_2', 'loan_purpose_4', 'loan_purpose_5',
       'loan_purpose_31', 'loan_purpose_32', 'loan_term_180.0',
       'loan_term_240.0', 'loan_term_300.0', 'loan_term_360.0',
       'loan_term_120', 'loan_term_180', 'loan_term_240', 'loan_term_300',
       'loan_term_360', 'loan_term_420', 'loan_term_480', 'loan_term_60',
       'loan_term_84', 'prepayment_penalty_term_0',
       'prepayment_penalty_term_2', 'prepayment_penalty_term_6',
       'prepayment_penalty_term_12', 'prepayment_penalty_term_18',
       'prepayment_penalty_term_24', 'prepayment_penalty_term_36',
       'intro_rate_period_1', 'in

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score, classification_report

# Create a pipeline with preprocessing and model
logistic_model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=3000))

# Fit the model on the training data
logistic_model.fit(X_train, y_train)

# Predict on the test data
y_pred = logistic_model.predict(X_test)

# Calculate the accuracy
logistic_accuracy = accuracy_score(y_test, y_pred)
print(f'Logistic Regression Accuracy: {logistic_accuracy:.4f}')

# Generate and print the classification report
report = classification_report(y_test, y_pred, target_names=['Class 0', 'Class 1'])

Logistic Regression Accuracy: 0.7868


In [ ]:
print(report)

              precision    recall  f1-score   support

     Class 0       0.83      0.72      0.77      5315
     Class 1       0.76      0.85      0.80      5373

    accuracy                           0.79     10688
   macro avg       0.79      0.79      0.79     10688
weighted avg       0.79      0.79      0.79     10688



In [ ]:
from sklearn.metrics import precision_score, f1_score, recall_score
print(precision_score(y_test, y_pred), f1_score(y_test, y_pred), recall_score(y_test, y_pred))

0.7558716506781343 0.8004203520448375 0.8505490415038154


In [ ]:
lr_coefficients = np.abs(logistic_model.named_steps['logisticregression'].coef_[0])
feature_names = X_test.columns
normalized_lr_weights = lr_coefficients / lr_coefficients.sum()
lr_weights_dict = {feature_names: normalized_lr_weights for feature_names,
                   normalized_lr_weights in zip(feature_names, normalized_lr_weights)}

In [ ]:
cont_dict_lr= {k: lr_weights_dict[k] for k in continuous if k in lr_weights_dict}

cat_dict_lr = {k: v for k, v in lr_weights_dict.items() if k not in continuous}
print(cont_dict_lr)
print(cat_dict_lr)

{'county_code': 0.0005351534974824161, 'census_tract': 0.0007184589215704486, 'loan_amount': 0.02039844306808137, 'loan_to_value_ratio': 0.0430554295135898, 'property_value': 0.008017878226386953, 'income': 0.003286098485632583}
{'preapproval': 0.004620236454186613, 'lien_status': 0.01691947239542368, 'negative_amortization': 0.009441033194274627, 'interest_only_payment': 0.0036555851030849176, 'balloon_payment': 0.0010421072058606961, 'construction_method': 0.004235418499744765, 'applicant_sex': 0.0009249525165287016, 'applicant_ethnicity': 0.015981169765521226, 'Mixed': 0.004390442395467588, 'AI or AN': 0.0032769043829829914, 'Asian': 0.010880130501399726, 'Black or AA': 0.0018220718131831135, 'NH or PI': 9.678077239930693e-05, 'White': 0.017739745240549616, 'loan_purpose_1': 0.0007858089161925198, 'loan_purpose_2': 0.000500392307500447, 'loan_purpose_4': 0.005012787247394622, 'loan_purpose_5': 0.0, 'loan_purpose_31': 0.008332369775782052, 'loan_purpose_32': 0.002449256384138754, 'lo

In [ ]:
from sklearn.preprocessing import StandardScaler
from scipy.spatial.distance import pdist, squareform
scaler= StandardScaler()
scaled_continuous_lr = scaler.fit_transform(X_test[cont_dict_lr.keys()])

dist_matrix_continuous_lr = numba_weighted_euclidean(np.array(scaled_continuous_lr), np.array(list(cont_dict_lr.values())))

In [ ]:
print(dist_matrix_continuous_lr)

[[0.         0.23879686 0.27138545 ... 0.40376077 0.2389242  0.39863214]
 [0.23879686 0.         0.06438895 ... 0.16869777 0.04951923 0.17033596]
 [0.27138545 0.06438895 0.         ... 0.1485713  0.08364013 0.14018778]
 ...
 [0.40376077 0.16869777 0.1485713  ... 0.         0.16930568 0.05773941]
 [0.2389242  0.04951923 0.08364013 ... 0.16930568 0.         0.16810592]
 [0.39863214 0.17033596 0.14018778 ... 0.05773941 0.16810592 0.        ]]


In [ ]:
dist_matrix_categorical_lr = numba_weighted_hamming_distance(np.array(X_test[cat_dict_lr.keys()], dtype=np.int32), np.array(list(cat_dict_lr.values())))

In [ ]:
print(dist_matrix_categorical_lr)
combined_distances_lr = dist_matrix_continuous_lr + dist_matrix_categorical_lr

[[0.         0.17914946 0.13916412 ... 0.19668712 0.09933785 0.29762343]
 [0.17914946 0.         0.24168229 ... 0.25151297 0.18180348 0.24197981]
 [0.13916412 0.24168229 0.         ... 0.26808554 0.18145469 0.3506786 ]
 ...
 [0.19668712 0.25151297 0.26808554 ... 0.         0.18909562 0.29009137]
 [0.09933785 0.18180348 0.18145469 ... 0.18909562 0.         0.23040745]
 [0.29762343 0.24197981 0.3506786  ... 0.29009137 0.23040745 0.        ]]


In [ ]:
average_distance_lr = np.mean(combined_distances_lr)
average_distance_lr

0.4595399112339706

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Initialize the Random Forest model
rf_model = RandomForestClassifier(random_state=42)

# Fit the model on the training data
rf_model.fit(X_train, y_train)

# Predict on the test data
rf_pred = rf_model.predict(X_test)

# Calculate the accuracy
rf_accuracy = accuracy_score(y_test, rf_pred)
print(f'Random Forest Accuracy: {rf_accuracy}')

# Generate and print the classification report
rf_report = classification_report(y_test, rf_pred, target_names=['Class 0', 'Class 1'])
print(rf_report)

Random Forest Accuracy: 0.8310254491017964
              precision    recall  f1-score   support

     Class 0       0.86      0.79      0.82      5315
     Class 1       0.81      0.87      0.84      5373

    accuracy                           0.83     10688
   macro avg       0.83      0.83      0.83     10688
weighted avg       0.83      0.83      0.83     10688



In [ ]:
print(precision_score(y_test, rf_pred), f1_score(y_test, rf_pred), recall_score(y_test, rf_pred))

0.809366869037294 0.837852397198779 0.8684161548483157


In [ ]:
rf_coefficients = np.abs(rf_model.feature_importances_)
normalized_rf_weights = rf_coefficients / rf_coefficients.sum()
rf_weights_dict = {feature_names: normalized_rf_weights for feature_names,
                   normalized_rf_weights in zip(feature_names, normalized_rf_weights)}
print(rf_weights_dict)

{'county_code': 0.04007096345032093, 'census_tract': 0.057877187281704864, 'preapproval': 1.5028055801856578e-05, 'lien_status': 0.007479347022309313, 'loan_amount': 0.05629071802934597, 'loan_to_value_ratio': 0.11548627330197453, 'negative_amortization': 7.987306886361677e-05, 'interest_only_payment': 0.020379714292114746, 'balloon_payment': 0.0001945491060318176, 'property_value': 0.0711371782261101, 'construction_method': 0.0007625884515648942, 'income': 0.09194922160586703, 'applicant_sex': 0.012384402154963496, 'applicant_ethnicity': 0.010409424042048648, 'Mixed': 0.0022822120830114107, 'AI or AN': 0.0016146024430083949, 'Asian': 0.007510633863362145, 'Black or AA': 0.0038852031979263956, 'NH or PI': 0.001287902054985319, 'White': 0.008524121779931733, 'loan_purpose_1': 0.0035183827007472736, 'loan_purpose_2': 0.009339765358079033, 'loan_purpose_4': 0.00935409210590207, 'loan_purpose_5': 0.0, 'loan_purpose_31': 0.006084635829296688, 'loan_purpose_32': 0.0018021820667322706, 'loan_

In [ ]:
cont_dict_rf= {k: rf_weights_dict[k] for k in continuous if k in rf_weights_dict}

cat_dict_rf = {k: v for k, v in rf_weights_dict.items() if k not in continuous}
print(cont_dict_rf)
print(cat_dict_rf)

{'county_code': 0.04007096345032093, 'census_tract': 0.057877187281704864, 'loan_amount': 0.05629071802934597, 'loan_to_value_ratio': 0.11548627330197453, 'property_value': 0.0711371782261101, 'income': 0.09194922160586703}
{'preapproval': 1.5028055801856578e-05, 'lien_status': 0.007479347022309313, 'negative_amortization': 7.987306886361677e-05, 'interest_only_payment': 0.020379714292114746, 'balloon_payment': 0.0001945491060318176, 'construction_method': 0.0007625884515648942, 'applicant_sex': 0.012384402154963496, 'applicant_ethnicity': 0.010409424042048648, 'Mixed': 0.0022822120830114107, 'AI or AN': 0.0016146024430083949, 'Asian': 0.007510633863362145, 'Black or AA': 0.0038852031979263956, 'NH or PI': 0.001287902054985319, 'White': 0.008524121779931733, 'loan_purpose_1': 0.0035183827007472736, 'loan_purpose_2': 0.009339765358079033, 'loan_purpose_4': 0.00935409210590207, 'loan_purpose_5': 0.0, 'loan_purpose_31': 0.006084635829296688, 'loan_purpose_32': 0.0018021820667322706, 'loan

In [ ]:
scaled_continuous_rf = scaler.fit_transform(X_test[cont_dict_rf.keys()])

dist_matrix_continuous_rf = numba_weighted_euclidean(np.array(scaled_continuous_rf), np.array(list(cont_dict_rf.values())))
dist_matrix_categorical_rf = numba_weighted_hamming_distance(np.array(X_test[cat_dict_rf.keys()], dtype=np.int32), np.array(list(cat_dict_rf.values())))
combined_distances_rf = dist_matrix_continuous_rf + dist_matrix_categorical_rf
average_distance_rf = np.mean(combined_distances_rf)
average_distance_rf

0.8572370892711186

In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

# Create a pipeline with preprocessing and the MLP model
# StandardScaler is used to scale the data for better performance of the MLP
mlp_model = make_pipeline(StandardScaler(), MLPClassifier(max_iter=1000,random_state=42, solver='sgd'))


# Fit the model on the training data
mlp_model.fit(X_train, y_train)

# Predict on the test data
mlp_pred = mlp_model.predict(X_test)

# Calculate the accuracy
mlp_accuracy = accuracy_score(y_test, mlp_pred)
print(f'MLP Accuracy: {mlp_accuracy}')

# Generate and print the classification report
mlp_report = classification_report(y_test, mlp_pred, target_names=['Class 0', 'Class 1'])
print(mlp_report)


MLP Accuracy: 0.8164296407185628
              precision    recall  f1-score   support

     Class 0       0.83      0.79      0.81      5315
     Class 1       0.80      0.84      0.82      5373

    accuracy                           0.82     10688
   macro avg       0.82      0.82      0.82     10688
weighted avg       0.82      0.82      0.82     10688



In [ ]:
print(precision_score(y_test, mlp_pred), f1_score(y_test, mlp_pred), recall_score(y_test, mlp_pred))

0.8015915119363395 0.8220892274211098 0.8436627582356225


In [ ]:
mlp_classifier = mlp_model.named_steps['mlpclassifier']
mlp_weights = mlp_classifier.coefs_[0]  # Weights from input layer to the first hidden layer
mlp_coefficients = np.abs(np.sum(np.abs(mlp_weights), axis=1))
normalized_mlp_weights = mlp_coefficients / mlp_coefficients.sum()
print(normalized_mlp_weights, feature_names)
mlp_weights_dict = {feature_names: normalized_mlp_weights for feature_names,
                   normalized_mlp_weights in zip(feature_names, normalized_mlp_weights)}
print(mlp_weights_dict)


[0.01055206 0.0103713  0.00957108 0.01235781 0.01807954 0.02098845
 0.00887065 0.01234504 0.01043735 0.01608852 0.01102316 0.01285472
 0.01176819 0.01197226 0.01044744 0.01080698 0.01053367 0.01116622
 0.01110811 0.00981755 0.01032072 0.0111844  0.0112587  0.00892853
 0.01101282 0.01114353 0.01003481 0.01040056 0.01094086 0.01303866
 0.00893138 0.00934926 0.00896867 0.00934687 0.01237837 0.0120272
 0.00978174 0.00946875 0.00895384 0.00986774 0.0139512  0.00889555
 0.00857175 0.00975915 0.00979351 0.01251116 0.01227033 0.00992038
 0.01520296 0.00911829 0.01334699 0.00956175 0.01177685 0.00885399
 0.00917389 0.01102493 0.01045442 0.01061272 0.01160125 0.01096507
 0.01088055 0.011482   0.01235985 0.01094951 0.01222369 0.01654312
 0.010657   0.01288065 0.01210191 0.00922296 0.00887062 0.01309959
 0.01296945 0.0093707  0.00982269 0.01283191 0.00914529 0.00986026
 0.00930764 0.01167238 0.01103076 0.01181112 0.00950003 0.01000951
 0.01154    0.01075726 0.01116872 0.01038932 0.01045866 0.01121

In [ ]:
cont_dict_mlp = {k: mlp_weights_dict[k] for k in continuous if k in mlp_weights_dict}

cat_dict_mlp = {k: v for k, v in mlp_weights_dict.items() if k not in continuous}
print(cont_dict_mlp)
print(cat_dict_mlp)

{'county_code': 0.010552057196783978, 'census_tract': 0.0103712962588143, 'loan_amount': 0.018079538752377985, 'loan_to_value_ratio': 0.020988451338355144, 'property_value': 0.016088517929471583, 'income': 0.012854715891712191}
{'preapproval': 0.009571077814331643, 'lien_status': 0.01235781414859384, 'negative_amortization': 0.008870648730519046, 'interest_only_payment': 0.012345037899043879, 'balloon_payment': 0.01043734952040405, 'construction_method': 0.011023159425949955, 'applicant_sex': 0.011768192730762536, 'applicant_ethnicity': 0.011972261341822827, 'Mixed': 0.010447442011796494, 'AI or AN': 0.010806976174651737, 'Asian': 0.010533665001345949, 'Black or AA': 0.01116622484809856, 'NH or PI': 0.011108113519560037, 'White': 0.009817552779123466, 'loan_purpose_1': 0.010320721639374432, 'loan_purpose_2': 0.01118440440628658, 'loan_purpose_4': 0.011258699046371383, 'loan_purpose_5': 0.008928526008014028, 'loan_purpose_31': 0.011012819614230012, 'loan_purpose_32': 0.01114353311006739

In [ ]:
scaled_continuous_mlp = scaler.fit_transform(X_test[cont_dict_mlp.keys()])

dist_matrix_continuous_mlp = numba_weighted_euclidean(np.array(scaled_continuous_mlp), np.array(list(cont_dict_mlp.values())))
dist_matrix_categorical_mlp = numba_weighted_hamming_distance(np.array(X_test[cat_dict_mlp.keys()], dtype=np.int32), np.array(list(cat_dict_mlp.values())))
combined_distances_mlp = dist_matrix_continuous_mlp + dist_matrix_categorical_mlp
average_distance_mlp = np.mean(combined_distances_mlp)
average_distance_mlp

0.4543323346808169

In [ ]:
def hamming_similarity(data):
    vals, counts = np.unique(data, return_counts=True)
    most_frequent_element = vals[np.argmax(counts)]

    similarity_count = np.sum(data == most_frequent_element)

    similarity_ratio = similarity_count / len(data)
    return similarity_ratio



In [ ]:
print(hamming_similarity(y_pred))

0.5656811377245509


In [ ]:
print(hamming_similarity(rf_pred))

0.5393899700598802


In [ ]:
print(hamming_similarity(mlp_pred))

In [ ]:
X_train.drop(['AI or AN', 'Asian', 'Black or AA', 'NH or PI', 'White', 'Mixed', 'applicant_ethnicity', 'applicant_sex'], axis=1,inplace=True)
X_test.drop(['AI or AN', 'Asian', 'Black or AA', 'NH or PI', 'White', 'Mixed', 'applicant_ethnicity', 'applicant_sex'], axis=1,inplace=True)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score, classification_report

# Create a pipeline with preprocessing and model
logistic_model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=3000))

# Fit the model on the training data
logistic_model.fit(X_train, y_train)

# Predict on the test data
y_pred = logistic_model.predict(X_test)

# Calculate the accuracy
logistic_accuracy = accuracy_score(y_test, y_pred)
print(f'Logistic Regression Accuracy: {logistic_accuracy:.4f}')

# Generate and print the classification report
report = classification_report(y_test, y_pred, target_names=['Class 0', 'Class 1'])

Logistic Regression Accuracy: 0.7876


In [ ]:
from sklearn.metrics import precision_score, f1_score, recall_score
print(precision_score(y_test, y_pred), f1_score(y_test, y_pred), recall_score(y_test, y_pred))

0.7550550715107677 0.8018505586592178 0.8548297040759353


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Initialize the Random Forest model
rf_model = RandomForestClassifier(random_state=42)

# Fit the model on the training data
rf_model.fit(X_train, y_train)

# Predict on the test data
rf_pred_un = rf_model.predict(X_test)

# Calculate the accuracy
rf_accuracy = accuracy_score(y_test, rf_pred_un)
print(f'Random Forest Accuracy: {rf_accuracy}')

# Generate and print the classification report
rf_report = classification_report(y_test, rf_pred, target_names=['Class 0', 'Class 1'])
print(rf_report)

Random Forest Accuracy: 0.8313061377245509
              precision    recall  f1-score   support

     Class 0       0.86      0.79      0.82      5315
     Class 1       0.81      0.87      0.84      5373

    accuracy                           0.83     10688
   macro avg       0.83      0.83      0.83     10688
weighted avg       0.83      0.83      0.83     10688



In [ ]:
print(precision_score(y_test, rf_pred_un), f1_score(y_test, rf_pred_un), recall_score(y_test, rf_pred_un))

0.8089304257528557 0.8383104654291095 0.8699050809603573


In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

# Create a pipeline with preprocessing and the MLP model
# StandardScaler is used to scale the data for better performance of the MLP
mlp_model = make_pipeline(StandardScaler(), MLPClassifier(max_iter=1000,random_state=42, solver='sgd'))


# Fit the model on the training data
mlp_model.fit(X_train, y_train)

# Predict on the test data
mlp_pred = mlp_model.predict(X_test)

# Calculate the accuracy
mlp_accuracy = accuracy_score(y_test, mlp_pred)
print(f'MLP Accuracy: {mlp_accuracy}')

# Generate and print the classification report
mlp_report = classification_report(y_test, mlp_pred, target_names=['Class 0', 'Class 1'])
print(mlp_report)


MLP Accuracy: 0.8221369760479041
              precision    recall  f1-score   support

     Class 0       0.85      0.78      0.81      5315
     Class 1       0.80      0.86      0.83      5373

    accuracy                           0.82     10688
   macro avg       0.82      0.82      0.82     10688
weighted avg       0.82      0.82      0.82     10688



In [ ]:
print(precision_score(y_test, mlp_pred), f1_score(y_test, mlp_pred), recall_score(y_test, mlp_pred))

0.7997237569060773 0.8297357814599196 0.8620882188721385


In [ ]:
print(hamming_similarity(y_pred))

0.5691429640718563


In [ ]:
print(hamming_similarity(rf_pred))
print(hamming_similarity(mlp_pred))

0.5406062874251497
0.5419161676646707
